AT_COMMANDS = [
    "ATI",
    "AT+CMEE=1",
    "AT!PRIID?",
    "AT!IMAGE?",
    "ATI8",
    "AT!GSTATUS?",
    "AT+CPIN?",
    "AT+CIMI",
    "AT!PCINFO?",
    "AT!CUSTOM?",
    "AT+CREG?",
    "AT+CGREG?",
    "AT+CEREG?",
    "AT+CGPADDR=1",
    "AT!SELRAT?",
    "AT+CGDCONT?",
    "AT!UIMS?",
    "AT!IMPREF?",
    "AT!BAND?",
    'AT!ENTERCND="A710"',
    "AT!BAND?",
    "AT!HWID?",
    "AT!USBCOMP?",
    "AT!USBSPEED?",
    "AT!USBPID?",
    "AT!USBINFO?",
    "AT!LTEINFO?",
    "AT!NRINFO?",
    "AT+COPS?",
]

AT_COMMANDS_HL78 = [
    "ATI",
    "AT+CMEE=1",
    "AT+KSRAT?",
    "AT+KBNDCFG?",
    "AT+CIMI",
    "AT+CPIN?",
    "AT+CCID?",
    "AT+CGSN",
    "AT+HWREV",
    "AT+CGDCONT?",
    "AT+KCARRIERCFG?",
    "AT+CEDRXS?",
    "AT+CPSMS?",
    "AT+KSIMDET?",
    "AT+KSIMSEL?",
    "AT+CREG?",
    "AT+CEREG?",
    "AT+KUSBCOMP?",
    "AT&V",
    "AT+IPR?",
    "AT+CSQ",
    "AT+KSLEEP?",
    "AT+KNWSCANCFG?",
    "AT+KTEMPMON?",
    "AT+KCERTSTORE?",
    "AT+KTCPCFG?",
    "AT+KUDPCFG?",
    "AT+KIPOPT?",
    "AT+WDSC?",
    "AT+WDSG",
    "AT+NVBU=2",
    "AT+COPS?",
]

AT_COMMAND_COPS = "AT+COPS=?"

DEFAULT_TIMEOUT = 60
DEFAULT_BAUDRATE = 115200
STATUS_FILE_PATTERN = "status_{model}_{timestamp}.txt"
