name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8.x'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8

    # - name: Run linting
    #   run: flake8 .

    - name: Run tests with unittest
      id: run-tests
      run: |
        test_output=$(python -m unittest discover tests)
        echo "::set-output name=test_output::$test_output"

    - name: Print test results
      if: always()
      run: |
        echo "Test Results:"
        echo "${{ steps.run-tests.outputs.test_output }}"